name: deploy

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Server
        uses: Sanch13/eng-rus-dict@main
        with:
          host: ${{ HOST }}
          username: ${{ USERNAME }}
          port: ${{ PORT }}
          key: ${{ SSHKEY }}
          script: "cd /home/sanch/www/ && touch text.txt"
